### ISSUE TITLE
Implement checklistBeforeChange

### ISSUE THREAD

**Issue by ozba** [vitalets/checklist-model#101]
Hi,
in my implementation I need to keep at least one check box checked at all times.
I've added to the model watch if(current.length > 1) before removing:

    scope.$watch(attrs.ngModel, function(newValue, oldValue) {
      if (newValue === oldValue) { 
        return;
      } 
      var current = getter(scope.$parent);
      if (angular.isFunction(setter)) {
        if (newValue === true) {
          setter(scope.$parent, add(current, value, comparator));
        } else {
			if(current.length > 1)
			{
				setter(scope.$parent, remove(current, value, comparator));
			}
        }
      }

      if (checklistChange) {
        checklistChange(scope);
      }
    });

The problem is that the UI has already changed to unchecked while the model did not change.
Anyone has a suggestion on how to change the checkbox back to "checked" state, or even better to catch it before it changed to checked?

Live example here, try to uncheck all and see that when the check boxes are all unchecked (what I'm trying to prevent) the model stays not empty (which is good but not enough):
http://jsfiddle.net/Ebv3p/641/

**Comment by beradrian** [comment]
There's already a discussion to implement such functionality: #15

**Comment by beradrian** [comment]
Implemented in 0.8.0.

**Comment by beradrian** [comment]
Here is the SO question: http://stackoverflow.com/questions/33730504/disallow-unchecking-of-all-checkboxes-in-angularjs/33768271#33768271
