### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by nagraj321** [vitalets/checklist-model#102]
I have requirement where we will be getting thousands of Objects from the back-end and show it on the UI. Showing all these object on a single page looks very complex. Just wondering can we use pagination with **Array of objects (pick object)**??

Thanks,
Nagaraju.

**Comment by beradrian** [comment]
This will require some form of server-side code to implement synchronization of the same array between pages. It don't think it's worth the effort designing and implementing such a feature in an exclusively client side UI component.
What you can do is actually maintain the entire array and work on only a subarray in the page. Then moving from one page to another will also imply to send the page subarray and copying it to the entire one on the server side.
