### ISSUE TITLE
The preselected checkbox is not on the checklist until toggled off and on

### ISSUE THREAD

**Issue by kamilkp** [vitalets/checklist-model#104]
See http://plnkr.co/edit/1Ef6d7udy5NXTRKtGUR7?p=preview

**Comment by beradrian** [comment]
I have only problem here. What happens if there is an inconsistency between ngModel and checklistModel? Let's say that ngModel is true, but checklistModel doesn't contain the value? Or the other way around?

**Comment by beradrian** [comment]
Just curios - why don't you use for initialization the `checklist-model`?

**Comment by beradrian** [comment]
So, using the checklistModel instead of ngModel solved this. I guess it is fine to leave it like this and close this issue. What do you think?

**Comment by kamilkp** [comment]
Yep

Kamil Pękala

Dnia 7 gru 2015 o godz. 11:33 Adrian Ber <notifications@github.com> napisał(a):

**Comment by beradrian** [comment]
Thanks! Anyway I added to the documentation comments about ngModel and a link to this issue. Many thanks for your involvement.
