### ISSUE TITLE
using required or ng-required with checklist-model

### ISSUE THREAD

**Issue by jondthompson** [vitalets/checklist-model#108]
It would be nice to have an example on how to use this with angular/html5's form validation.

**Comment by beradrian** [comment]
You should use `checklist-change` or `checklist-before-change` and set the validity in there. I'll try to prepare an example.

**Comment by jongunterfv** [comment]
I second this. Would be super helpful to at least have an example in the docs on how to require a checklist model. If you add `required` or `ng-required` to each checkbox, you make the user check every option, which isn't the desired behavior.

**Comment by beradrian** [comment]
Here's the example: http://jsfiddle.net/beradrian/7wt9q1ev/

**Comment by jondthompson** [comment]
That isn't what I'm asking for. I have a form that I'm validating, the submit button of which is disabled until form.$valid is true. I have a checklist that I want to integrate into that form. Anyhow, it's not a huge deal because I just put ' || userFundingList.length == 0' in my ng-disable directive, which solves the issue as well, albeit not cleanly.

**Comment by jondthompson** [comment]
please reopen this issue, as it isn't solved.

**Comment by beradrian** [comment]
Is this what you're looking for http://jsfiddle.net/beradrian/nbwcbejw/?

**Comment by jondthompson** [comment]
That looks good. Thanks. 

-- 
Jon Thompson
Evolve
515 360 1351

**Comment by clong365** [comment]
It's not so good enough.
When the checkboxes are in init state(none of them is checked or dirty), demoForm.role is {"$valid": true, "$invalid": false,"$error": {}}, but we expect {"$valid": false, "$invalid": true, "$error": { "required": true }

**Comment by beradrian** [comment]
You should use `checklist-change` in conjunction with `ng-init` to set the validity.

**Comment by robertogf** [comment]
`ng-required="!demoForm.role"` for each checkbox will sove, is only required while there's none checked

**Comment by martinoss** [comment]
based on the idea of @robertogf (did not work for me), this solved the problem for me: 
`ng-required="!user.roles.length"`
