### ISSUE TITLE
Remove excessive requirement input[type=checkbox] #2

### ISSUE THREAD

**Issue by mathpere** [vitalets/checklist-model#112]
Hi,

This issue is related to this one: https://github.com/vitalets/checklist-model/issues/53

Could you remove the following restriction?

```
if ((tElement[0].tagName !== 'INPUT' || tAttrs.type !== 'checkbox') && (tElement[0].tagName !== 'MD-CHECKBOX') && (!tAttrs.btnCheckbox)) {
        throw 'checklist-model should be applied to `input[type="checkbox"]` or `md-checkbox`.';
      }
```

Regards.

**Comment by beradrian** [comment]
What is the reason to do that? It makes sense to have this only on a checkbox.

**Comment by mathpere** [comment]
At this time, checklist-model allows or tries to allow: 
- input checkbox
- md-checkbox (material angular), 
- btn-checkbox (angular bootstrap).

Unfortunately, your code fails to allow btn-checkbox (cf my comment https://github.com/vitalets/checklist-model/issues/53#issuecomment-164737273)

1. I don't think you could support all those kind of libraries.
2. As I already said, the new version of angular-bootstrap renamed btn-checkbox into ui-btn-checkbox, so checklist-model is already outdated.
3. I don't see any good reason to do this agressive checking. Drop a line of documentation should be enough.

**Comment by beradrian** [comment]
I see your point, but users can easily misuse this directive, even unintentionally. If checklist is outdated, then a new version can be released.

On the other hand, I'm not that keen on that check. So I would let the community decide. I will leave this issue open so that people can comment on it. If you get at least a few votes for your proposal, I would merge the PR. What do you think - does it sound right?

**Comment by jingignoli** [comment]
+1

**Comment by PtiPingouin** [comment]
+1

**Comment by celestian02** [comment]
+1

**Comment by yohannrub** [comment]
+1

**Comment by stevematyas** [comment]
+1

**Comment by vsellier** [comment]
+1

**Comment by beradrian** [comment]
I guess that there are enough votes to merge your PR. One kind request for all the voters - at least give a star to the project - your opinion mattered and influenced the project. Thank you!

**Comment by mathpere** [comment]
700 stars :)
Thanks for the PR!
