### ISSUE TITLE
Support for min max number of choices

### ISSUE THREAD

**Issue by smene** [vitalets/checklist-model#114]
Hi,
I have been trying to extend your code in order to support what is quite often useful in surveys (check at most N options) or please select at least two of the following options.
The validation should be consistent to the ngForms validation so that when the directive is used within a form, at least $invalid of the underlying form will be to true/false automatically.
Typically this is done with a $validator (since AngularJS v1.3) but the way you manipulate ngModel is pretty difficult.

**Comment by beradrian** [comment]
This is already addressed by checklist-change to set the validity or checklist-before-change to enable/disable selection.
Here's an example: http://jsfiddle.net/beradrian/nbwcbejw/

**Comment by smene** [comment]
Hi there (sorry for my late reply),
1. This is true, but you have to cause a change in order for the "checklist-change" event to fire. What happens when the binding to the model is already in faulty state ? In your jsfiddle example just remove the $scope.user.roles initialization to undefined or empty array and the button will still be enabled even though no selection is in place.

2. I believe that there is something not working with the checklist-change in case that the checklist-model is a directive in a template of another directive i.e.
<div ng-repeat="option in getChoicesOfQuestion()">
	<label>
        <input
        	name="gid57526e4c_ccf7_4d2b_92f1_754d31590771" 
        	type="checkbox" 
        	checklist-model="esPsVal[esQuestion.Code]" 
        	checklist-value="option.Value"
        	checklist-change="esqsection.gid57526e4c_ccf7_4d2b_92f1_754d31590771.$setValidity('required', esPsVal[esQuestion.Code].length > 0)">{{option.Description}}

	</label>
</div>

3. I suggest that the scope binding to the checklist-change attribute should be of type &. Suppose that the argument of this attribute is an expression that needs to be evaluated before function execution.

Thanks

**Comment by santiph** [comment]
This worked like a charm to me: 

ng-disabled="!checked && myDataChecklistModel.length > 3"

**Comment by beradrian** [comment]
@smene, I'm also answering with some delay.
1. You should simply first validate the model and then bind it. If you move the validation to a function it is really easy.
2. I would definitely evaluate your suggestion and see if it's fit to be integrated in a next version.

**Comment by beradrian** [comment]
For min-max I guess you can easily write a separate directive and add custom validators through it.

**Comment by smene** [comment]
Thnx a lot for your prompt response.
I will look to your suggestions and come back

**Comment by beradrian** [comment]
If you develop such a directive, I can add it to the examples.
