### ISSUE TITLE
Checking changes in checklisValue not working for static object

### ISSUE THREAD

**Issue by colindeclue** [vitalets/checklist-model#116]
If I set my object in the html (e.g., from a razor view) like so:

    <input type="checkbox" checklist-model="selected" checklist-value="{'id': '@link.Id', 'title': '@link.Title'}" checklist-comparator=".id"/> @link.Title

Then it gets into a loop digesting when checking to see if the value has changed. Needs to respect the checklest-comparator?

**Comment by beradrian** [comment]
Could you create an example in jsfiddle or something similar?

**Comment by joostbaptist** [comment]
My pull request https://github.com/vitalets/checklist-model/pull/120 will fix this.

**Comment by beradrian** [comment]
I will close this issue as the PR fix was merged.
