### ISSUE TITLE
Plnkr Examples Not Working

### ISSUE THREAD

**Issue by beatelite** [vitalets/checklist-model#117]
Hey, great directive. I was literally writing something from scratch but realized that I should run a google search on "checkbox filters" vs "faceted search" - which wasn't turning up any results. Imagine my relief!

I noticed your plnkr examples don't seem to be working: http://plnkr.co/edit/pZLF0KesMDnIap0eCfSG?p=preview
http://plnkr.co/edit/QPLk98pCljp8dFtptSYz?p=preview

Your Js fiddles and Live Demo seem to work fine.

**Comment by beradrian** [comment]
Instead of the first one see http://plnkr.co/edit/0UrMwtiNQxJJbVWnYgSt?p=preview. Second one is updated. I will update the README too. Thanks!
