### ISSUE TITLE
Default results to show all?

### ISSUE THREAD

**Issue by beatelite** [vitalets/checklist-model#118]
Before I get to deep, I didn't see anything in the examples or in the forum about this so thought I'd ask:

I am attempting to create a faceted search where there's a list of results by default and then the user can select checkboxes to filter that result set in real time. See this as an example: 
https://facetwp.com/demo/

I see that checklist-model examples do not show all results by default but need to have a checkbox selected for anything to show. 

Am I missing something or is there no way to do this?

**Comment by beradrian** [comment]
I guess by "show all results" you actually want to have all the checkboxes selected. This can be easily done by populating the checklistModel with all the possible values.
Please feel free to comment if this doesn't answer to your question.

**Comment by beatelite** [comment]
Not quite, like the example I linked to, not all checkboxes are selected by default but all results are showing and then the user can filter from there. Here's another example but done in angular - albeit not in a directive:
http://jsfiddle.net/rzgWr/19/

**Comment by beradrian** [comment]
The jsfiddle above does not use checklistModel. Meantime I fixed the Plunkr examples and you can see in there all the checkboxes selected.

**Comment by beatelite** [comment]
I understand they don't use your directive. What i'm trying to ascertain is whether I can accomplish the same type of faceted search with your directive?

Thanks for the updates on the plnkrs.

**Comment by beradrian** [comment]
Yes, of course you can use the same with this directive. You can have a filter that returns all, when there are no checkboxes selected.

**Comment by beatelite** [comment]
Great news. When you say " you can have a filter the returns all"

Can you point me to an example of this by chance?

**Comment by beradrian** [comment]
I was referring to any filter, implemented as a scope function or in a pure Angular way: https://docs.angularjs.org/api/ng/filter/filter. No, unfortunately I don't have an example, because this is not related to the checklist-model project.
