### ISSUE TITLE
One by one selection is not updating to the model some times.

### ISSUE THREAD

**Issue by esh-cherukuri** [vitalets/checklist-model#119]
Hi,
i had modified your demo file a little bit and it is working sometimes in fiddle and sometimes it is not working but when i copy the same to my application it is not working properly completely can you check my file at http://jsfiddle.net/1m7q1v7r/

The problem is when i click on check all it is selecting all but the check boxes are not filling. if i select one by one the model is not updating. it model works only for check all and uncheck.

Thanks,
Rajesh.

**Comment by beradrian** [comment]
I just tried your example and it works for me..I clicked on "check all" - all the checkboxes are ticked and the model is updated. Then I clicked the checkboxes one by one to uncheck them and check them again. They're ticked accordingly and the model is updated.
