### ISSUE TITLE
How to deal with more complex json objects?

### ISSUE THREAD

**Issue by redcricket** [vitalets/checklist-model#121]
Hi,

I really like your checklist-model.  It has saved me a lot of work.  It is quite useful.  But I am having a problem and I have plunkr here: http://plnkr.co/edit/aPCEBV5e9Pb5np9iaY2l?p=preview (which works now :) 

And a detailed question here: http://stackoverflow.com/questions/34914941/how-to-get-checkboxes-to-initialize-based-on-model 

Thanks!

**Comment by beradrian** [comment]
I answered on SO. Let's move the discussion there.

**Comment by redcricket** [comment]
I fixed the plunker example ... can you take a look?
