### ISSUE TITLE
Click and dblclick event

### ISSUE THREAD

**Issue by SzabZol** [vitalets/checklist-model#123]
Hello!

I would like to use click (with timeout), and dblclick event on checklist-model.

Is it possible?
Any idea? (jQuery and Angular also suitable)

Thanks!

**Comment by beradrian** [comment]
Just use ngClick on each checkbox.

**Comment by SzabZol** [comment]
Yes... But I use custom template, because I use FontAwesome icons:
<span class="permission-icon fa fa-pencil" model="accessVm.saveData.permissions" checklist-value="value" uib-btn-checkbox></span>

**Comment by beradrian** [comment]
And why you cannot use ngClick? Could you please create a plunkr or jsfiddle example?

**Comment by SzabZol** [comment]
Here: http://jsfiddle.net/vLcx4sdn/
Timeout not working.

**Comment by beradrian** [comment]
The timeout is called. I just put a `console.log` inside and it got printed out.
