### ISSUE TITLE
checklistChange is called n times depending of n checklist-model in ng-repeat

### ISSUE THREAD

**Issue by sant123** [vitalets/checklist-model#124]
Hi, I'm going to explain this with an example:

```
<label ng-repeat="role in roles">
      <input type="checkbox" checklist-model="user.roles" checklist-value="role.id" data-checklist-change="test2()"> {{role.text}}
</label>
```

So, test2() is going to be called when some checkbox is checked; that's is correct. But if I repeat the code above with another ng-repeat: 

```
<label ng-repeat="role in roles">
      <input type="checkbox" checklist-model="user.roles" checklist-value="role.id" data-checklist-change="test2()"> {{role.text}}
</label>
<label ng-repeat="role in roles">
      <input type="checkbox" checklist-model="user.roles" checklist-value="role.id" data-checklist-change="test2()"> {{role.text}}
</label>
```

The test2() method is going to be called twice. I've done a plunker to show you how ngChange works in angular in these cases and how checklistChange should work as well.

https://plnkr.co/edit/09m0jr2V1IVKX7JdupjG

**Comment by beradrian** [comment]
What I don't like to this approach is that you have two different functions to be called when the model has changed, coming from two different checkboxes, inside two different ngRepeat's, then the second one and subsequent ones will not be called.

Unless the community decides otherwise through a MASSIVE vote, this won't be fixed.

**Comment by sant123** [comment]
They are not different functions, both call the same function and is not correct that one checkbox call n times a ng click, that's why I made an example with ng model with angular. That's the expected result, not to call ng click for example twice if there's another checklist model. Either way it's an advise I'm giving you, it's your choice if you want to fix it or not, finally it's your library.

**Comment by beradrian** [comment]
Take a look at this modified example: https://plnkr.co/edit/5VmAfyvquYYRVYHfoMsd?p=preview - there are different functions.
And this is a public library, it just happen for me to be the most active maintainer. And it happened in the past to implement things that I wasn't totally agreeing: #112. What's a library good for if people don't use it or if it doesn't meet their needs.
