### ISSUE TITLE
multiple checks at one go!!

### ISSUE THREAD

**Issue by himanshuchaudhary** [vitalets/checklist-model#125]
Hi, 

I would like to get multiple checks if I click one check box.

**Comment by beradrian** [comment]
What do you mean by multiple checks?

**Comment by himanshuchaudhary** [comment]
it means that i want to check one item..which should simultaneously check
other dependent items(not all but some)


[image: image001]

Regards,
*Himanshu Chaudhary*
Contact : +91-9035662923 | himanshu.chaudhary@hp.com
<himanshu.chaudhary@hp.com%20%7C>
Hewlett-Packard Company | 39/40 | Digital park | Hp Avenue | EC-1 |
Bangalore | Karnataka | India

**Comment by beradrian** [comment]
If you want to this then you need to either use `checklistChange` or `scope.$watch` on the model.
