### ISSUE TITLE
Checkbox not getting selected on click

### ISSUE THREAD

**Issue by sauravGit** [vitalets/checklist-model#129]
My HTML code :

<div class="col-xs-12 col-sm-12 col-md-2">
          <div class="row">
            <div class="col-md-12">
              <div class="row">
              <div class="col-xs-9 col-sm-9 col-md-4">
              <span style="font-weight: 400; font-size: medium; color: #f5f5f5; padding-bottom: 15px; padding-left: 5px" id="ba12">Affiliate:</span>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-4">
                <a style="font-weight: 400; font-size: 15px; color: #f5f5f5; padding-bottom: 15px;" ng-click="checkAllAffiliate();">Select All</a>
              </div>
              </div>
              </div>
              </div>
              <div class="input-group">

            <label ng-repeat="affiliate in affiliateDataInput" style="  width:150px; position:relative; left: -20px; display:inline-block; vertical-align:middle; color: #f5f5f5">
              <input type="checkbox" data-checklist-model="affiliateDataOutput.userinput" data-checklist-value="affiliate" class="input" checked> {{affiliate.name}}
            </label>

          </div>
        </div>

JS code in the controller : 

function globalPartnerFilterList()  // This method gets the data from the Server
      {
        var q = globalFilterQuery("AFFILIATE_DISPLAY_NAME.raw");
        esClientIndirect.search
        (
          {
            index: esIndex1,
            type: esType1,
            size: 0,
            body: q
          },
          function (error, response)
          {
            var data =  response.aggregations.column.buckets;
            var list = [];
            var i =0;
            for (var k in data)
            {
              element = data[k].key;
              list.push({id : i , name: element, filterBy : "AFFILIATE_DISPLAY_NAME.raw"})
              i= i+1;
            }
            $scope.affiliateDataInput =  list; // the list 
          });
      }
      $scope.affiliateDataOutput = {userinput: []};
      $scope.checkAllAffiliate = function()
      {
        $scope.affiliateDataOutput = angular.copy($scope.affiliateDataInput);
      };

Data Sample : 

{ filterBy: "column_name_1" , id : 0,  name: "Customer_1" }
{ filterBy: "column_name_2" , id : 1,  name: "Customer_2" }
{ filterBy: "column_name_3" , id : 2,  name: "Customer_3" }

When I click on Select All() or on check box model is not getting updated. Am I doing anything wrong?

**Comment by beradrian** [comment]
Could you please prepare an example on plunkr, jsfiddle or anything similar? It would save some time, avoid confusion so that I can fix it faster, if needed. Thank you.

**Comment by sauravGit** [comment]
Sorry for the late response. I think now it's working. :+1: There was a conflict with other JS file.
