### ISSUE TITLE
checklist-value can be a function?

### ISSUE THREAD

**Issue by askie** [vitalets/checklist-model#131]
`<input type="checkbox" name="radio1" checklist-model="ngModel" checklist-value="itemData(item,sku)">
`

error:

`
Error: $rootScope:infdig
Infinite $digest Loop
10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: getChecklistValue","newVal":{"item":{"item_id":1,"company_id":160417265,"outer_id":"111111","cid":1,"title":"111111","shape_id":40,"unit_id":43,"volume_unit_id":47,"weight_unit_id":54,"volume":2222,"weight":100,"stocks_warning":11,"created_at":"2016-04-17T10:34:16.000Z","desc":"<p>12311111111111111111111111111
`

**Comment by beradrian** [comment]
Could you please build an example on plunkr, jsfiddle or something similar?

**Comment by beradrian** [comment]
I will close this for now, but please do come back with an example.
