### ISSUE TITLE
Checkboxes do not update after selection and deselection

### ISSUE THREAD

**Issue by djdavisdt** [vitalets/checklist-model#136]
Hi - not sure what I'm doing wrong, but the checkboxes are not updating after the initial selection and deselection. It appears that they are no longer being watched. Please see plnkr

https://plnkr.co/edit/3Kji4EngmsmTv9ETmdlz?p=preview

**Comment by beradrian** [comment]
Please check this out: https://plnkr.co/edit/cQYv1vLR6n963RqOKmKE?p=preview
