### ISSUE TITLE
Checkboxes do not stay checked.

### ISSUE THREAD

**Issue by wpsmith** [vitalets/checklist-model#139]
I have a site that I am working on using `checklist-model`, and I am posting here per the Github README. I apologize as I am unable to make the Plunker/JSFiddle. If you can, please use the site credentials below (please obfuscate).

To reproduce the issue:

1. Log into the site
Site: https://opentruk.com/wp-login.php
User: `wps`
PW: `FYzMrVwy07HNLXO0OChyritt`
1. Go to https://opentruk.com/search/
1. Click on `All Filters`
1. Click on `Grilled Sandwiches`
It will check and immediately uncheck.

You will want to check out these files in particular:
* Controller: https://opentruk.com/wp-content/plugins/geodirectory-opentruk/js/app.controller.main.js?ver=1465180706
* Template Cache: https://opentruk.com/wp-content/plugins/geodirectory-opentruk/js/app.run.js?ver=1465180319
* Directives: https://opentruk.com/wp-content/plugins/geodirectory-opentruk/js/app.directives.foodtruk.js?ver=1465153522

Essentially, I want to have everything available to me via `$rootScope` primarily to link the buttons `Verified Open` and `Open` buttons to the Filters dropdown containing those as checkboxes (which I do not have setup at the moment due to the checkboxes not remaining checked). Please let me know what I am doing wrong. I can give you more information if you need!

**Comment by beradrian** [comment]
Hi,

Unfortunately your code is too complex and is kind of unpractical and very time consuming for me to debug. If you can isolate your issue in a simpler example, I can definitely take a look. For the moment, I will close this one, but feel free to open a new one with the isolated example. 

On a side note, I will recommend you to take a look at the model - display, log it in the console as it changes etc. Which btw, is not in the $rootScope.

You can also ask on StackOverflow - don't forget to tag it with `checklist-model`.
