### ISSUE TITLE
How to choose more than one value in table using checklist-model 

### ISSUE THREAD

**Issue by gopi1989** [vitalets/checklist-model#141]
Hi, 

I am Having a table with 5 columns,I used checkbox for one of the column and get the selected values through checklist-model value.My Intention is to if i click the check box ,I have to retrieve two column values in table. If it is possible to extract two values?

Thanks with Regards,
Gopi krishnan.R

**Comment by beradrian** [comment]
You can simply use as value an object of which properties will be displayed in the two (or five) columns.
