### ISSUE TITLE
Export the module name

### ISSUE THREAD

**Issue by mgol** [vitalets/checklist-model#143]
The package.json's `main` field should point to a file that assigns the module name to `module.exports`. That's what most of Angular modules are currently doing, see e.g. the [`angular-animate` module](https://github.com/angular/bower-angular-animate/blob/v1.5.7/index.js).

**Comment by chatii2412** [comment]
It's already implemented at v0.10.0.
The problem is that v0.10.0 is not released and published to npm.
Please resolve this.
Thanks.

**Comment by beradrian** [comment]
v0.10.0 was released.
