### ISSUE TITLE
What if I need to select only one value, not multiples ?

### ISSUE THREAD

**Issue by Vikasg7** [vitalets/checklist-model#144]
All the examples covers the scenario of selecting multiple items. I need a functionality where I select one check box, other previously select checkbox should lost its select. So we could always select only one check box.
If this functionality is already there and I have missed it. Please let me know. !!
Thanks in advance.

**Comment by beradrian** [comment]
You can implement it using `checklist-change` to run code after the change and deselect the previous one. But wouldn't this be better implemented using radio buttons?

**Comment by Vikasg7** [comment]
http://stackoverflow.com/a/38194899/4850220
I made this better one. Achieving the same thing.

Regards,
