### ISSUE TITLE
Add a none-of-above option to the list

### ISSUE THREAD

**Issue by mkhanal** [vitalets/checklist-model#147]
From a list of checkbox, there should be one, which when checked, unchecks all others and is unchecked when anything else is checked. This is so that a usual use case of "None of the above" option can be easily catered for. It would be good to have this allow both unsetting all the values or setting a special value for the none-of-above options

**Comment by beradrian** [comment]
These kind of cases can be easily handled by `checklist-before-change` or `checklist-change`.
