### ISSUE TITLE
Doesn't work for arrays of integers

### ISSUE THREAD

**Issue by andrewlphilpott** [vitalets/checklist-model#150]
I'm working with some data that includes an array of integers (i.e. [1, 3, 6, 9, 12]) and noticed that checklist-model doesn't work with the data because it's assuming data is strings. I was able to get it to work by adding the following code to the `contains`, `add`, and `remove` functions:

```
if(!isNaN(item)) {
  item = parseInt(item);
}
```

Any chance we could get something like this added to the directive?

**Comment by beradrian** [comment]
Could you please write a PR with tests?

**Comment by andrewlphilpott** [comment]
Sorry, forgot to come back to this but it looks like someone else created a PR for it: https://github.com/vitalets/checklist-model/pull/157

**Comment by beradrian** [comment]
PR merged
