### ISSUE TITLE
Pop

### ISSUE THREAD

**Issue by phanivaranasi** [vitalets/checklist-model#151]
Hi Team,
I'm trying to restrict duplicate selections in my checked list,
Below is js code

![image](https://cloud.githubusercontent.com/assets/6230353/19618514/02cc32b4-986a-11e6-9780-463bf614617b.png)

Below is html code
![image](https://cloud.githubusercontent.com/assets/6230353/19618519/2cfb8030-986a-11e6-8617-5eeb0cfaedfd.png)

Now, when pop is used checklist-model is getting poped but its not reflecting in html,  duplicate checkbox is still checked, how it can be unchecked ?

Thanks
Phaneendra

**Comment by beradrian** [comment]
Use `checklist-before-change` instead `checklist-change` and return a boolean value to accept or not the change.
