### ISSUE TITLE
Have checklist-before-change accept function returning promise

### ISSUE THREAD

**Issue by GustavSt** [vitalets/checklist-model#153]
It would be nice if you could provide a function returning a promise. 
The promise being rejected giving same result as today having a false expression and if it is successfully resolved is like having a today having true expression.

**Comment by beradrian** [comment]
The problem is that a promise asynchronous and by the time that the promise is accepted/rejected, the change would have been already accepted.

**Comment by GustavSt** [comment]
Maybe it wasn't clear in the feature request, but obviously for it to work with promises it would need some work do make it asynchronous. 

But maybe that is not something you've planned on doing?

**Comment by beradrian** [comment]
`checklist-change` can be made to work asynchronously, but not checklist-before-change` because the latter needs a value that must be returned immediately. Or it can be made asynchronously, but the value will be ignored.

Any other idea?
