### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by leonardochaia** [vitalets/checklist-model#155]
Hello, great directive you've got here.
I'm wondering if you'd be willing to publish to NuGet.
I know you already have Bower and NPM packages, but maybe you are willing to add another one.
I may get the time to do a pull request with a .nuspec file if you are interested.

Thanks,
Leo.

**Comment by beradrian** [comment]
If you create the PR, of course.

**Comment by ramarivera** [comment]
+1
Truly a great directive!!
