### ISSUE TITLE
Not an issue but a big thank you!

### ISSUE THREAD

**Issue by Notifium** [vitalets/checklist-model#158]
Hi,
Just wanted to say thanks so much your hard work on this - it's just saved me hours of banging my head against the table whilst trying to work out how to implement dynamic numbers of checkboxes derived from a one-to-many relationship in the DB.

Well done! And I love the flexibility of how you can tie the data and the UI together in so many ways - arrays, properties, objects, etc. Superb work!

Regards,
Andy

**Comment by beradrian** [comment]
Thank you!
