### ISSUE TITLE
Allow data-attributes

### ISSUE THREAD

**Issue by terebentina** [vitalets/checklist-model#16]
Normally you are allowed to write attribute directives as either checklist-model or data-checklist-model to be html5 compatible. $attrs normalizes that.
However, using data-checklist-model crashes chrome in your jsfiddle example and on my local I get a recursion problem.

Edit: the problem happens only with checklist-model, not with checklist-value.

**Comment by gms5002** [comment]
+1.  I just wasted an entire day tracking this down and came up with the same solution as @tdakhla

**Comment by samherrmann** [comment]
@tdakhla take a look at my suggestion [here](https://github.com/vitalets/checklist-model/pull/52#discussion_r25570661) on how to use Angular's attribute normilization.

**Comment by tdakhla** [comment]
@samherrmann Yeah that's a much better approach.  Updated my comment.

**Comment by beradrian** [comment]
Could you please check the current version and how it solves this issue?
