### ISSUE TITLE
Enhance this directive to work with IE8

### ISSUE THREAD

**Issue by tdakhla** [vitalets/checklist-model#18]
As it stands, this directive doesn't work with IE8 since the code is trying to set the type of the input to a checkbox (which isn't allowed) instead of evaluating it:

```javascript
if (tElement[0].tagName !== 'INPUT' || !tElement.attr('type', 'checkbox')) {
```

should be changed to:

```javascript
if (tElement[0].tagName !== 'INPUT' || tElement.attr('type') != 'checkbox') {
```

Plus, it just makes more sense to evaluate the type instead of setting it.

**Comment by sazo** [comment]
Fixed with #25
