### ISSUE TITLE
Add possibility to have multi-level lists (tree)

### ISSUE THREAD

**Issue by alexzaporozhets** [vitalets/checklist-model#21]
Something similar to: http://dev.sencha.com/deploy/ext-4.0.1/examples/tree/check-tree.html

**Comment by beradrian** [comment]
You already can do this. Check this out: http://plnkr.co/edit/QPLk98pCljp8dFtptSYz?p=preview

**Comment by sureshkoduri** [comment]
Hi Bro,

The above plnkr is not working. Can you please provide a working example?
