### ISSUE TITLE
watch (line 59) causes crash

### ISSUE THREAD

**Issue by busterkikas** [vitalets/checklist-model#22]
If the list disappear, it is undefined. At this point, watch the line 59 will try to add a value to a variable undefined. 

Should be corrected to get something like this:

     scope.$watch('checked', function(newValue, oldValue) {
     if (newValue === oldValue) {
          return;
     }
     var current = getter(scope.$parent);
     if (scope.$parent && current && value) {
          if (newValue === true) {
               setter(scope.$parent, add(current, value));
          } else {
               setter(scope.$parent, remove(current, value));
          }
     }"

**Comment by sazo** [comment]
i know this is a long time ago but will you make a example on http://plnkr.co/ that demonstrate the problem.

**Comment by beradrian** [comment]
We will need a test case that will set the checklistModel to null.

**Comment by beradrian** [comment]
A set to null was added and it's working fine.
