### ISSUE TITLE
issue with angular >= 1.2.15

### ISSUE THREAD

**Issue by rjbordon** [vitalets/checklist-model#28]
Hi @vitalets,

I'm trying to use your directive with angular 1.2.15 but with no success. I checked that your demo site and your code jsfiddle are referencing to angular 1.0.8. Do you know if your directive is ready for use against angular 1.2.15? or I missing something else?

Thx in advance.

**Comment by sazo** [comment]
@rjbordon 
Hallo, i just join the project to maintain it (and, if time, add new features).
I have not tested it on >1.0.8 angular version, but when i got the time i will look in to it and run my test on newer versions.

**Comment by StateBarofArizona** [comment]
I am using Angular v1.4.4 and as above, nothing happens.  It's like the checklist-model is not recognized.

**Comment by Lorthirk** [comment]
It seems everything is fine here, angular 1.4.6 and angular-material 0.11.0...

**Comment by Lorthirk** [comment]
Hello, I'm using angular 1.4.6 and angular-material 0.11.0 and it seems everything is fine here...

**Comment by beradrian** [comment]
Anyway, I'll be working on moving to latest version and use angular as a dependency, not included statically.

**Comment by beradrian** [comment]
I upgraded to Angular 1.4.8 and everything seems fine. If it doesn't work for you please reopen.
