### ISSUE TITLE
Checklist items are not binding to scope, when checked individually.

### ISSUE THREAD

**Issue by twelve6** [vitalets/checklist-model#36]
Following the example exactly as on the Demo site, when the checkboxes are clicked individually they do not bind to the scope. I have inspected it on the demo site with the angular inspector, on my own site (Angular 1.2.16), with in a Yo Angular app (Angular 1.2.6), with no luck. Am I incorrect to assume that the checkbox (checkbox-value) value is to bind to scope when clicked individually or does this require buttons with ng-click directives?

**Comment by sazo** [comment]
#40 is now merged in and the problem should bee fixed. :) thx for repporting the bug.
