### ISSUE TITLE
HTML5 compatibility

### ISSUE THREAD

**Issue by raajon** [vitalets/checklist-model#39]
Hello i've found such a bug:

this work just fine:
\<input type="checkbox" checklist-model="user.roles" checklist-value="role">

and this crash the application
\<input type="checkbox" x-checklist-model="user.roles" x-checklist-value="role">
\<input type="checkbox" data-checklist-model="user.roles" data-checklist-value="role">

**Comment by sazo** [comment]
duplicate of #16
