### ISSUE TITLE
Fails on minification

### ISSUE THREAD

**Issue by kodeine** [vitalets/checklist-model#42]
I am using codeSleeve minifcation for laravel4. 
checklist-model fails on single checkbox select. SelectAll and unCheck all works normal.
Looks like checked=true is not being set in checklist-model on single checkbox selects.

**Comment by sazo** [comment]
Definitely a good feature and added to the todo list.

**Comment by agibson-fl** [comment]
+1

I just pushed this code to our dev server after working in a feature branch for quite some time... and ran into this problem.  Ugh.

**Comment by jessemorton** [comment]
+1

**Comment by beradrian** [comment]
I introduced a test case for a single checkbox and it works fine. Do you still have this issue with the latest version? I will close this ticket, please reopen it if the problem persists.
