### ISSUE TITLE
Remove excessive requirement input[type=checkbox]

### ISSUE THREAD

**Issue by mathpere** [vitalets/checklist-model#53]
Hi,

In order to use checklist-model with [btn-checkbox from ui-bootstrap] (http://angular-ui.github.io/bootstrap/#/buttons), I had to use a forked version of checklist-model by commenting these two lines:
```
if (tElement[0].tagName !== 'INPUT' || tAttrs.type !== 'checkbox') {
    throw 'checklist-model should be applied to `input[type="checkbox"]`.';
}
```

I can confirm this works like a charm. This requirement seems a little bit excessive. Could it be improved or removed?

**Comment by beradrian** [comment]
I added a check like this 
    if ((tElement[0].tagName !== 'INPUT' || tAttrs.type !== 'checkbox')
      		&& (tElement[0].tagName !== 'MD-CHECKBOX')
      		&& (!tAttrs.btnCheckbox)) {

**Comment by mathpere** [comment]
Hi,

Thanks for your support!

However, the recommended way to use btn-checkbox is to add attribute btn-checkbox or btn-checkbox=""

=> tAttrs.btnCheckbox = ""
=> !tAttrs.btnCheckbox = false
=> So I still can not use checklist-model.

Also, the new version of angular bootstrap (0.14) rename this directive into uib-btn-checkbox which will broke again your directive.

Could you not simply remove this checking? 

The developer should know how he can use your directive.

Regards.
