### ISSUE TITLE
Label on other line then ng-repeat

### ISSUE THREAD

**Issue by cskiwi** [vitalets/checklist-model#54]
hi

I'm using materializecss, and there a checkbox has to have HTML like this:
```html
<p>
    <input type="checkbox" id="test5" />
    <label for="test5">Red</label>
</p>
```
so the label is below the input, is it possible to use this module then?
```html
<div ng-repeat="role in roles">
    <input type="checkbox" checklist-model="user.roles" checklist-value="role.id">
    <label>
        {{role.text}}
    </label>
</div>
```
wasn't sucesfull

**Comment by cskiwi** [comment]
Nevermind after messing around with it I found the sollution;
you just need to add the id, i used a simple prefix of `checkbox_` in the following example

```html
<div ng-repeat="role in roles">
    <input type="checkbox" id="checkbox_{{role.id}}" checklist-model="user.roles" checklist-value="role.id">
    <label for="checkbox_{{role.id}}">
        {{role.text}}
    </label>
</div>
```

**Comment by mccpp** [comment]
Thanks, this issue helped me with a different css library.
