### ISSUE TITLE
Possible to Change ng-model Name for Each List?

### ISSUE THREAD

**Issue by darrindickey** [vitalets/checklist-model#71]
I'm trying to use this on multiple checklists on one page. I need to save the selections of each list to localStorage. However, all of the checklist-model lists use the same ng-model name. So, it will only save all of the selections as one object.

Is there a way to change this for each list without changing checklist-model's core code?

**Comment by beradrian** [comment]
Now you can specify `ng-model` name. If not specified it will use the default `checked`
