### ISSUE TITLE
$dirty is only updated when touch the last checkbox in the group

### ISSUE THREAD

**Issue by paulboony** [vitalets/checklist-model#72]
See below. If colors array is ['red', 'green', 'blue'], then ticking then un-ticking red or green doesn't affect $dirty state. Only when I tick and untick blue, then required error message will show up.
```
<form name="myForm">
  <div class="checkbox" ng-repeat="color in colors">
      <label>
        <input type="checkbox" name="color"
              checklist-model="formData['selectedColors']" 
              checklist-value="color" 
              ng-required="formData['selectedColors'].length == 0">
              {{color}}
      </label>
  </div>
  <p class="help-block error" 
    ng-show="myForm['color'].$error.required && myForm['color'].$dirty">
    This field is required.
  </p>
</form>
```

**Comment by beradrian** [comment]
Could you please provide a plunkr example?

**Comment by charco09** [comment]
I have added functionality to our local version of the directive to mark the form field as $touched after a checkbox in the list has changed. I looked into a pull request but I don't have permission. How does that work to have it reviewed and see if it also solves your issue?

**Comment by beradrian** [comment]
Just create a pull request from your forked repository. I'll review it and merge it.

**Comment by bbodenmiller** [comment]
Could not reproduce see https://github.com/vitalets/checklist-model/pull/78#issuecomment-147073709

**Comment by beradrian** [comment]
Then I'll close the issue.
