### ISSUE TITLE
Works only with subarray?

### ISSUE THREAD

**Issue by pgeza** [vitalets/checklist-model#73]
If I bind it to a simple array it is not working:
$scope.SelectedItems: []
It works only with:
$scope.anything= {
	SelectedItems: []
};

Am I right?
The problem is with the  function:
$scope.UnCheckAll = () => {
		$scope.SelectedCertificateBlocks = [];
	};
it updates the model but doesn't uncheck the checkboxes

**Comment by kiroushi** [comment]
I am also experiencing this issue.

**Comment by beradrian** [comment]
Does it work with `$scope.SelectedCertificateBlocks.splice(0, $scope.SelectedCertificateBlocks.length);` instead of `$scope.SelectedCertificateBlocks = [];`?

**Comment by beradrian** [comment]
I updated all the tests and everything seems fine. I will close this ticket please reopen it if the problem persists.
