### ISSUE TITLE
Feature Request - More uses to comparator

### ISSUE THREAD

**Issue by junalmeida** [vitalets/checklist-model#76]
I want to use the checklist-value option to bind the entire object. But I do not want to write my own comparator function. It would be nice to use checklist-comparator to something like this:
```
            <label ng-repeat="rule in c.Rules">
                <input type="checkbox" name="checkBox[]" checklist-model="c.SelectedRule" checklist-value="rule" checklist-comparator="rule.Id"> {{rule.Name}}
            </label>
```

**Comment by beradrian** [comment]
Now you can use the comparator like this `.Id` - it must start with dot('.'). Example is added to demos and tests.
