### ISSUE TITLE
How can I add an image to the check box and label?

### ISSUE THREAD

**Issue by TerrySchroeder** [vitalets/checklist-model#77]
I need to show the user a checkbox, an image, and title and allow them to select as many as they choose. ie. show the user various samples of granite and a title and ask them to pick all their favorite ones.

**Comment by beradrian** [comment]
You can add the image, text and checkbox inside the label.

**Comment by TerrySchroeder** [comment]
HI Adrian,

Thank you. Do you have an example? After spending 30 years with COBOL, this is VERY new to me.

Any help would be more than appreciated.

Terry Schroeder

**Comment by beradrian** [comment]
Something like this

    <label ng-repeat="sample in samples">
        <img ng-src="sample.image"/>
        <input type="checkbox" checklist-model="selectedSamples" checklist-value="sample"> {{sample.text}}
    </label>

See the examples at http://vitalets.github.io/checklist-model/ for the controller part.

**Comment by TerrySchroeder** [comment]
Thank you!!!
