### ISSUE TITLE
why is there no new line character after each option, please help

### ISSUE THREAD

**Issue by sfaizan** [vitalets/checklist-model#80]
![checklist-model](https://cloud.githubusercontent.com/assets/9317338/9192668/b3fdad9a-402a-11e5-88ed-dea7418edc1a.JPG)

code we have is :
	label(ng-repeat='interest in interests')
        input(type='checkbox', checklist-model='UI.student.interests', checklist-value='interest')
	| {{interest}} 
		

i cant get the next item to be in a new line , like shown is the example

**Comment by beradrian** [comment]
This has nothing to do with the checklist-model directive. Check the generated HTML if it's well formed and the CSS for the label.
