### ISSUE TITLE
Problem with change checklist-model

### ISSUE THREAD

**Issue by isimonov** [vitalets/checklist-model#81]
I noticed that if I change checklist-model as in the example below (select something and Press Clean), then the checkbox will not reset and no they cease to work.

http://plnkr.co/edit/5FvNVvMXDuitH9UcJXM1?p=preview

**Comment by beradrian** [comment]
Try 

    userRoles.splice(0, userRoles.length);

See in the documentation why.

**Comment by isimonov** [comment]
Thanks!
