### ISSUE TITLE
Tag 0.5.0

### ISSUE THREAD

**Issue by mrUmberto** [vitalets/checklist-model#82]
bower checklist-model#0.5.0 not-cached git://github.com/vitalets/checklist-model.git#0.5.0
    bower checklist-model#0.5.0    resolve git://github.com/vitalets/checklist-model.git#0.5.0
    bower checklist-model#0.5.0     ENORESTARGET No tag found that was able to satisfy 0.5.0

    Additional error details:
    Available versions: 0.4.0, 0.2.4, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0

**Comment by beradrian** [comment]
Fixed. And better check 0.6.0.
