### ISSUE TITLE
Version 0.5.0 is not associated with tag 0.5.0

### ISSUE THREAD

**Issue by fhellwig** [vitalets/checklist-model#85]
Version 0.5.0 appears in the bower.json file on the master branch, but does NOT appear when switching to the 0.5.0 branch. The result is that a bower install results in the following:

    bower checklist-model#~0.5.0 mismatch Version declared in the json (0.2.4) is different than the resolved one (0.5.0)

**Comment by beradrian** [comment]
Fixed. And a new release 0.6.0 was added for simplicity.
