### ISSUE TITLE
Doesn't work with newer Angular versions

### ISSUE THREAD

**Issue by RedactedProfile** [vitalets/checklist-model#86]
I get weird anomalies when using this with Angular 1.4.x, such as all checkboxes checking at the same time, or null values. 

I noticed on your demo site you're using Angular 1.0.8. And I see in the code that an include to 1.2.11 is commented out in favor of the 1.0.8 version in usage now. My assumption here is simply that 1.2.11 doesn't work and 1.0.8 was reintroduced to bring the demo page back to a working condition. 

But I see changes made in the repo from less than a month ago, so this is active..

**Comment by beradrian** [comment]
Indeed this is a reported issue #28. I haven't tested with latest versions of Angular and this is right next on the todo list. I will close this issue as a duplicate. Please add any other comments to that issue.
