### ISSUE TITLE
Working with groupBy list.

### ISSUE THREAD

**Issue by duongtdvn** [vitalets/checklist-model#90]
I had an array like this: 
```javascript
$scope.players = [
  {name: 'Gene', team: 'alpha'},
  {name: 'George', team: 'beta'},
  {name: 'Steve', team: 'gamma'},
  {name: 'Paula', team: 'beta'},
  {name: 'Scruath', team: 'gamma'}
];
```

and in the view I create a list which groupBy the team like so:
```html
<ul>
  <li ng-repeat="(key, value) in players | groupBy: 'team'">
    Group name: {{ key }}
    <ul>
      <li ng-repeat="player in value">
        player: {{ player.name }}
      </li>
    </ul>
  </li>
</ul>
```

Currently when i click on check all, all players get checked but i want to make the checklist only check the player in each team. Is it possible to do it?

**Comment by beradrian** [comment]
Could you please create an example for this on Plunkr, JSFiddle or anything alike? I don't see the code for 'check all', the checkboxes or how you define the checklist-mode, but there isn't something like this built-in. On the other hand, you can easily do it.

**Comment by duongtdvn** [comment]
Hi, i got it sorted, but now i had another problem probably the UI conflict.
1, If i click checkAll, then all box got checked fine, after that i check any individual checked box it make all box unchecked.
2, If i check an individual box, then click checkAll, the previous individual box not getting update anymore until i click on it.

Please take a look at this plunkr: http://plnkr.co/edit/i4MEi7mKrffYKkRPTVbL?p=preview

I think it because of the ng-model which binding on the same [key] but if I remove the ng-model out of the input, then the checkAll can not uncheck all the checked boxes.

**Comment by beradrian** [comment]
I think you should use ` checklist-value="player.name"` or ` checklist-value="player"` instead of  `checklist-value="item.id"`. And instead of modifying the selectedValues array, try to empty it and add all the desired values.

**Comment by duongtdvn** [comment]
Oops, sorry for the typo, just changed to player instead of item.id but it didn't fix.

**Comment by beradrian** [comment]
Do you still have this issue?

**Comment by beradrian** [comment]
I will close this issue until other details will be provided. Please feel free to reopen if necessary.
