### ISSUE TITLE
I want full control over the UI

### ISSUE THREAD

**Issue by TroyWolf** [vitalets/checklist-model#91]
In simple cases, it's great that the code creates the checkbox elements for you. However, I need more control over the layout of the checkboxes in the group--multiple columns of checkboxes in a group for example.

When I went looking for "angular best practices for checkbox groups", I was hoping to find a solution that does almost exactly what you offer but where I apply it to my own checkbox group HTML.

I'm new to Angular, but for me, one of the reasons I'm attracted to Angular is the ability to get back to simple HTML DOM and away from having javascript create all the DOM. For my checkbox groups, they will remain pretty much static--I don't need to dynamically data-drive the creation of that DOM. I just need a good 2-way method to manage what is checked as a group.

**Comment by beradrian** [comment]
You can use the `ng-repeat`, but this is not mandatory. You can have your own checkboxes linked together by the checklist-model.

**Comment by TroyWolf** [comment]
Thanks. I will try to get this working. You might update your nice examples page to show a "Static list of checkboxes" example. I am also wondering now if there would be a way to set the checklist-model on the parent container rather than repeat that in 20 checkbox elements in the group. Thanks for putting this code out there.

**Comment by beradrian** [comment]
I wouldn't go on the path of setting this in the parent container. In the same container you may have different groups and it would become confusing and cluttered.

**Comment by beradrian** [comment]
I added a new issue for static list example:  #92 .
