### ISSUE TITLE
Malfunctions, when used with angular-translate

### ISSUE THREAD

**Issue by mavarazy** [vitalets/checklist-model#95]
With a simple Object, and following markup:

    <label ng-repeat="(key, text) in roles">
        <input type="checkbox" checklist-model="user.roles" checklist-value="key"> {{text}}
    </label>

But when adding properly configured translate:

    <label ng-repeat="(key, text) in roles">
        <input type="checkbox" checklist-model="user.roles" checklist-value="key" translate> {{text}}
    </label>

it does not trigger update events for user.roles anymore

**Comment by beradrian** [comment]
Do you have a JSFiddle, Plunkr example or anything alike?

**Comment by pratik14** [comment]
@mavarazy Do you want to change value of checkbox along with text?

**Comment by beradrian** [comment]
The tests are working and I cannot reproduce this issue. Until more detailed example of the issue is provided, I will close it. Please feel free to reopen it.
