### ISSUE TITLE
check all issue

### ISSUE THREAD

**Issue by nikhilvm1993** [vitalets/checklist-model#96]
I have created a function associated with check list-change.that function call each time when check-list model value changes

and we also have a checkAll function to select and unselectAll,when selecting all ,if there are 10 check lists,that change function call 10 times.how can i avoid that??

<div ng-app="app" ng-controller="Ctrl">
  <label ng-repeat="role in roles">
    <input type="checkbox" checklist-model="user.roles" checklist-value="role.id" checklist-change="caller();"> {{role.text}}
  </label>
  <br>
  <button ng-click="checkAll()">check all</button>
  <button ng-click="uncheckAll()">uncheck all</button>
  <button ng-click="checkFirst()">check first</button>
  <br><br>
  user.roles {{ user.roles | json }}
</div>

var app = angular.module("app", ["checklist-model"]);

app.controller('Ctrl', function($scope) {
$scope.roles = [
    {id: 1, text: 'guest'},
    {id: 2, text: 'user'},
    {id: 3, text: 'customer'},
    {id: 4, text: 'admin'}
  ];
  $scope.user = {
    roles: [2, 4]
  };
  $scope.checkAll = function() {
    $scope.user.roles = $scope.roles.map(function(item) { return item.id; });
  };
  $scope.uncheckAll = function() {
    $scope.user.roles = [];
  };
  $scope.checkFirst = function() {
    $scope.user.roles.splice(0, $scope.user.roles.length); 
    $scope.user.roles.push(1);
  };
    $scope.caller = function(){
        alert("called");
    }

});

**Comment by beradrian** [comment]
I don't see the HTML code, but most probably you associated the change function with each checkbox - which is normal. But this means that for every change in every checkbox that function will be called.

You can still avoid that with a flag. Before actually doing the change in checkAll/uncheckAll set the flag and unset it after. Then in the callback function check the flag before doing any action.
